name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev
    
    - name: make build system
      run: cmake -B build

    - name: build portaudio
      run: cmake --build build --target portaudio
      
    - name: build binary
      run: cmake --build build --target cPlayer

    - name: build all (tests)
      run: cmake --build build

    - name: run tests
      run: 	GTEST_COLOR=1 ctest --test-dir build -V
